/*
    HOW MANY MISSED THE BOAT? - OOP FINAL PROJECT - BSCS-2D     
    Olitoquit, Aileen B.    
    Olimverio, Marc Justine B.      
    Medina, Kathlene
*/

import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//edi wow
/**
 *
 * @author jionv
 */
public class HowManyMissedTheBoat extends javax.swing.JFrame {
    Random random = new Random();
    int answer;
    
    //Array for the dice values
    int[] values = new int[6];
            
    public HowManyMissedTheBoat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: 
     * Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblBox1 = new javax.swing.JLabel();
        lblBox2 = new javax.swing.JLabel();
        lblBox3 = new javax.swing.JLabel();
        lblBox4 = new javax.swing.JLabel();
        lblBox5 = new javax.swing.JLabel();
        lblBox6 = new javax.swing.JLabel();
        tfAnswer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        lblConfirmAnswer = new javax.swing.JLabel();
        btnRoll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("How Many Missed the Boat? - OOP FINAL PROJECT");
        setBounds(new java.awt.Rectangle(750, 300, 0, 0));

        jPanel3.setBackground(new java.awt.Color(60, 77, 89));

        jPanel2.setBackground(new java.awt.Color(161, 188, 215));

        jPanel1.setBackground(new java.awt.Color(161, 188, 215));
        jPanel1.setLayout(new java.awt.GridLayout(2, 3, 20, 20));

        lblBox1.setIcon(new javax.swing.ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\4.png")); // NOI18N
        lblBox1.setText("jLabel1");
        lblBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBox1.setMinimumSize(new java.awt.Dimension(122, 122));
        lblBox1.setPreferredSize(new java.awt.Dimension(122, 122));
        jPanel1.add(lblBox1);

        lblBox2.setIcon(new javax.swing.ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\1.png")); // NOI18N
        lblBox2.setText("jLabel1");
        lblBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBox2.setMinimumSize(new java.awt.Dimension(122, 122));
        lblBox2.setPreferredSize(new java.awt.Dimension(122, 122));
        jPanel1.add(lblBox2);

        lblBox3.setIcon(new javax.swing.ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\3.png")); // NOI18N
        lblBox3.setText("jLabel1");
        lblBox3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBox3.setMinimumSize(new java.awt.Dimension(122, 122));
        lblBox3.setPreferredSize(new java.awt.Dimension(122, 122));
        jPanel1.add(lblBox3);

        lblBox4.setIcon(new javax.swing.ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\1.png")); // NOI18N
        lblBox4.setText("jLabel1");
        lblBox4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBox4.setMinimumSize(new java.awt.Dimension(122, 122));
        lblBox4.setPreferredSize(new java.awt.Dimension(122, 122));
        jPanel1.add(lblBox4);

        lblBox5.setIcon(new javax.swing.ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\3.png")); // NOI18N
        lblBox5.setText("jLabel1");
        lblBox5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBox5.setMinimumSize(new java.awt.Dimension(122, 122));
        lblBox5.setPreferredSize(new java.awt.Dimension(122, 122));
        jPanel1.add(lblBox5);

        lblBox6.setIcon(new javax.swing.ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\5.png")); // NOI18N
        lblBox6.setText("jLabel1");
        lblBox6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBox6.setMinimumSize(new java.awt.Dimension(122, 122));
        lblBox6.setPreferredSize(new java.awt.Dimension(122, 122));
        jPanel1.add(lblBox6);

        tfAnswer.setBackground(new java.awt.Color(255, 255, 255));
        tfAnswer.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        tfAnswer.setForeground(new java.awt.Color(0, 0, 0));
        tfAnswer.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOW MANY MISSED THE BOAT?");

        btnCheck.setBackground(new java.awt.Color(255, 255, 255));
        btnCheck.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnCheck.setForeground(new java.awt.Color(0, 0, 0));
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        lblConfirmAnswer.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        lblConfirmAnswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnRoll.setBackground(new java.awt.Color(255, 255, 255));
        btnRoll.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnRoll.setForeground(new java.awt.Color(0, 0, 0));
        btnRoll.setText("Roll");
        btnRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblConfirmAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblConfirmAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        answer = 0;
        try{ 
            //Non Duplicate Dice
            int nonDupDice = 0;
            
            //Creating an empty ArrayList
            ArrayList<Integer> ans = new ArrayList<>();
            for(int i : values){
                //checking if the element is already present or not
                if(!ans.contains(i)){
                    //Adding the element to the ArrayList if not present
                    ans.add(i);
                }
            }
            //adding all the elements in the nonDupDice
            for(int i : ans){
                nonDupDice += i;
            }
            
            //nonDupDice subtracted from the total value
            answer = 21 - nonDupDice;
            
            //calls the method that checks the answer
            checker();
            
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Please enter a number only!", 
                    "ERROR   ", 
                    HEIGHT);
        }  
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollActionPerformed
        //loop for displaying random icon in the Jlabels
        for(int i = 0; i <=5; i++){
                //assigns random value to the array index
                values[i] = random.nextInt(6);
                
                switch(i){
                    case 0:

                        switch(values[0]){
                            case 1:
                                lblBox1.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\1.png")); break;
                            case 2:
                                lblBox1.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\2.png")); break;
                            case 3:
                                lblBox1.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\3.png")); break;
                            case 4:
                                lblBox1.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\4.png")); break;
                            case 5:
                                lblBox1.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\5.png")); break;
                            case 6:
                                lblBox1.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\6.png")); break;
                            default:
                                break;  
                        } 
                        break;
                    case 1:
                        switch(values[1]){
                            case 1:
                                lblBox2.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\1.png")); break;
                            case 2:
                                lblBox2.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\2.png")); break;
                            case 3:
                                lblBox2.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\3.png")); break;
                            case 4:
                                lblBox2.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\4.png")); break;
                            case 5:
                                lblBox2.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\5.png")); break;
                            case 6:
                                lblBox2.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\6.png")); break;
                            default:
                                break;
                        }
                        break;
                    case 2:
                        switch(values[2]){
                            case 1:
                                lblBox3.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\1.png")); break;
                            case 2:
                                lblBox3.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\2.png")); break;
                            case 3:
                                lblBox3.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\3.png")); break;
                            case 4:
                                lblBox3.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\4.png")); break;
                            case 5:
                                lblBox3.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\5.png")); break;
                            case 6:
                                lblBox3.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\6.png")); break;
                            default:
                                break;
                        }
                        break;
                    case 3:
                        switch(values[3]){
                            case 1:
                                lblBox4.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\1.png")); break;
                            case 2:
                                lblBox4.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\2.png")); break;
                            case 3:
                                lblBox4.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\3.png")); break;
                            case 4:
                                lblBox4.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\4.png")); break;
                            case 5:
                                lblBox4.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\5.png")); break;
                            case 6:
                                lblBox4.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\6.png")); break;
                            default:
                                break;
                        }
                        break;
                    case 4:
                        switch(values[4]){
                            case 1:
                                lblBox5.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\1.png")); break;
                            case 2:
                                lblBox5.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\2.png")); break;
                            case 3:
                                lblBox5.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\3.png")); break;
                            case 4:
                                lblBox5.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\4.png")); break;
                            case 5:
                                lblBox5.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\5.png")); break;
                            case 6:
                                lblBox5.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\6.png")); break;
                            default:
                                break;
                        }
                        break;
                    case 5:
                        switch(values[5]){
                            case 1:
                                lblBox6.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\1.png")); break;
                            case 2:
                                lblBox6.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\2.png")); break;
                            case 3:
                                lblBox6.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\3.png")); break;
                            case 4:
                                lblBox6.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\4.png")); break;
                            case 5:
                                lblBox6.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\5.png")); break;
                            case 6:
                                lblBox6.setIcon(new ImageIcon("E:\\AILEEN\\CVSUSC\\pics\\6.png")); break;
                            default:
                                break;
                        }
                        break;
                    default: 
                        break;
                }
            }
        
    }//GEN-LAST:event_btnRollActionPerformed
    
    public void checker(){
        //converts String input to Integer
        int tfIntAnswer = Integer.parseInt(tfAnswer.getText());
        
        //checks whether the input answer is right or wrong
        if(answer == tfIntAnswer){
            lblConfirmAnswer.setText("Congratulations! You got the correct answer!");
        } else {
            lblConfirmAnswer.setText("Wrong! The correct answer is " + answer + "!");
        }
    }
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HowManyMissedTheBoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HowManyMissedTheBoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HowManyMissedTheBoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HowManyMissedTheBoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HowManyMissedTheBoat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnRoll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBox1;
    private javax.swing.JLabel lblBox2;
    private javax.swing.JLabel lblBox3;
    private javax.swing.JLabel lblBox4;
    private javax.swing.JLabel lblBox5;
    private javax.swing.JLabel lblBox6;
    private javax.swing.JLabel lblConfirmAnswer;
    private javax.swing.JTextField tfAnswer;
    // End of variables declaration//GEN-END:variables
}
